# Shad Abdullah, Intern ID - i23b0034s05

# Library Import

In [1]:
import numpy as np

# Problem 1

In [2]:
a = np.array([[1,2,3,4],[4,5,6,7]])

b = np.array([[10,11,12,13],[13,14,15,16]])
 
c = a + b

c

array([[11, 13, 15, 17],
       [17, 19, 21, 23]])

# Problem 2

In [3]:
a = np.array([[1, 2],[3, 4],[5, 6]])

multi = a * 5

multi

array([[ 5, 10],
       [15, 20],
       [25, 30]])

# Problem 3

In [4]:
iden_matrix = np.identity(10)

a = 5 * iden_matrix

a

array([[5., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 5., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 5., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 5., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 5.]])

# Problem 4

In [5]:
_1d_array = np.arange(100, 200, 5)

_3d_array = _1d_array.reshape(2, 2, 5)

_3d_array

array([[[100, 105, 110, 115, 120],
        [125, 130, 135, 140, 145]],

       [[150, 155, 160, 165, 170],
        [175, 180, 185, 190, 195]]])

# Problem 5

In [6]:
a = np.array([[1, 2],[3, 4]])

b = np.array([[5, 6],[7, 8]])

m = np.hstack((a, b))

m

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Problem 6

In [7]:
a = np.array([[1, 2],[3, 4]])

b = np.array([[5, 6],[7, 8]])

mv = np.vstack((a, b))

mv

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])